on:
  push:
    branches:
      - 'main'

jobs:
  podswap:
    uses: douglascdev/podswap@main
    with:
      pre-build-cmd: 'git pull'
      build-cmd: 'podman compose build'
      deploy-cmd: 'podman compose up -d --force-recreate'
    secrets:
      WEBHOOK_SECRET: ${{ secrets.WEBHOOK_SECRET }}
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}
